### ISSUE TITLE
Register This Package?

### ISSUE THREAD

**Issue by ChrisRackauckas** [sunoru/RandomNumbers.jl#17]
Is there a plan to register this package? I would like to be able to start using it to some extent, but it cannot be a dependency until it's registered.

**Comment by sunoru** [comment]
I'm sorry I missed this issue..

Actually as you can see there are still some issues left, which I don't know how to fix for now.

For example as I mentioned in this issue(https://github.com/sunoru/RNG.jl/issues/12), I couldn't find a good algorithm for sequencing the seed. Therefore it's not gauranteed to be correct when using this package, and that's why I haven't registered this package yet.

Anyway if one only uses RNGs which are confirmed to be good to use, such as `xoroshiro128plus` or `PCG` family this package works well.

I didn't realise it's necessary to be registered to be a dependency.. So maybe I should register it anyway and put a warning or something to warn the users?

**Comment by ChrisRackauckas** [comment]
I think it would be fine to register and warn. There's lots of usable stuff here, and it's reasonable to register early and let it improve over time.

**Comment by sunoru** [comment]
I have created a pull request. https://github.com/JuliaLang/METADATA.jl/issues/7888

**Comment by sunoru** [comment]
It's registered now.
