### ISSUE TITLE
Pkg.test() fails on Windows because of CR-LF

### ISSUE THREAD

**Issue by GregPlowman** [sunoru/RandomNumbers.jl#24]
On one of my PCs (which runs Windows 7), `Pkg.test()` fails.

Files in the `expected` sub-directory contain `CR-LF` (\r\n) pairs, whereas files created in the `actual` sub-directory contain only `LF` characters.

On another PC (which runs Windows 10), files in both sub-directories contain `LF` character only, and `Pkg.test()` succeeds.

Perhaps the GitHub download of `expected` files is different for these PCs.
I'm not sure what is different between these two PCs, other than the Windows version.

I have a Julia fix, which simply replaces `CR-LF` with `LF` before testing, and could submit a PR.
However, I was wondering if someone else can reproduce this and confirm it is a general issue, rather than just something peculiar to my machine.

**Comment by sunoru** [comment]
I tested and got the same issue on my Windows 10 laptop today. I think it's because the default configuration of LibGit2 (in the standard library of Julia) makes all files have `CR-LF` as linebreaks.

When writing text to a file, Julia by default uses `LF` and I thought it's the same when reading a file (but it's not). Modifying `@test_diff` is OK. I'm happy to merge your PR.

**Comment by GregPlowman** [comment]
Also noticed `test/generic.jl`
Is this file used? If not should it be deleted?

**Comment by sunoru** [comment]
It's for testing some generic functions and I'll update it.
